"""add unique constraint for feature rollouts

Revision ID: ad81ac032b5d
Revises: 89fe5939f877
Create Date: 2026-08-13 15:39:06.018087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad81ac032b5d'
down_revision: Union[str, Sequence[str], None] = '89fe5939f877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_feature_environment_rollout', 'feature_rollouts', ['feature_flag_id', 'environment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_feature_environment_rollout', 'feature_rollouts', type_='unique')
    # ### end Alembic commands ###
